In [3]:
import numpy as np

In [4]:
wade = np.array([[1,2],[4,5]])

In [5]:
wade.dtype

dtype('int64')

In [6]:

w = np.identity(3)

In [7]:
np.zeros_like(w)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
int_a = np.arange(10);
int_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
int_a.dtype

dtype('int64')

In [10]:
b = int_a.astype(float);

In [11]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
b.dtype

dtype('float64')

In [38]:
int_string = np.array(['33222.2','2.2','4.4'])
int_string
# intc.dtype


array(['33222.2', '2.2', '4.4'], dtype='|S7')

In [97]:
em = np.empty(10,'u2')
em

array([44928, 41721, 22054,     0, 45744, 41721, 22054,     0, 37824,
        6147], dtype=uint16)

In [105]:
b= int_a[3:5].copy()
b[1] = 2

In [107]:
b

array([3, 2])

In [152]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
                

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
arr[1:2,:]

array([[4, 5, 6]])

In [129]:
name = np.array(['wade','kobe','miami'])
name == 'miami'

array([False, False,  True])

In [141]:
mask = name != 'wade'

In [132]:
# name = ['wade','kobe','miami']
# name == 'miami'

In [142]:
mask
# arr [-(name == 'wade')]

array([False,  True,  True])

In [166]:
abb = arr[mask]
abb[:,:] = 1
abb
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
arr < 0

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [176]:
arr = np.random.randn(3,2,)
arr

array([[-0.51006517,  1.01952896],
       [-0.41158594, -1.68201096],
       [-0.76333334,  0.03451618]])

In [183]:
np.empty(8
        )

array([4.67998452e-310, 0.00000000e+000, 6.92534925e-310, 6.92536538e-310,
       6.92536537e-310, 6.92537204e-310, 6.92534923e-310, 0.00000000e+000])

In [192]:
arr.T

array([[-0.51006517, -0.41158594, -0.76333334],
       [ 1.01952896, -1.68201096,  0.03451618]])

In [216]:
arr = np.arange(32).reshape(2,2,2,2,2)
# arr.transpose(1,0,2)
arr.swapaxes(3,4)

array([[[[[ 0,  2],
          [ 1,  3]],

         [[ 4,  6],
          [ 5,  7]]],


        [[[ 8, 10],
          [ 9, 11]],

         [[12, 14],
          [13, 15]]]],



       [[[[16, 18],
          [17, 19]],

         [[20, 22],
          [21, 23]]],


        [[[24, 26],
          [25, 27]],

         [[28, 30],
          [29, 31]]]]])

In [234]:
x = np.random.randn(4)*10
print(x)
np.modf(x)

[ 18.86394575  17.63607098 -22.42783695  18.91882648]


(array([ 0.86394575,  0.63607098, -0.42783695,  0.91882648]),
 array([ 18.,  17., -22.,  18.]))

In [230]:
x  = np.random.randn(10)
xx  = np.random.randn(10)
xxx  = np.random.randn(10)
xxxx  = np.random.randn(10)
np.maximum(x,xx,xxx,xx)

ValueError: invalid number of arguments

In [242]:
a = np.arange(10).reshape(2,5)
b = np.ones([2,5])*3
np.mod(a,b)
np.ones(10)

TypeError: data type not understood

In [243]:
arr = np.random.randn(3,5)
np.dot(arr.T,arr)
np.dot(arr,arr.T)

array([[ 5.97685681,  5.9454188 , -7.60236398],
       [ 5.9454188 , 11.65177854, -8.33546034],
       [-7.60236398, -8.33546034, 11.04898279]])

In [257]:
x = np.arange(1,10)
print(x)
xs ,ys = np.meshgrid(x,x)
xs
ys

[1 2 3 4 5 6 7 8 9]


array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [267]:
# arr = np.arange(15).reshape(3,5)
arr = np.ones([3,5])
arr.sum(1)

array([5., 5., 5.])

In [286]:
arr = np.random.randn(4,5)
print(arr)
arr.sort(axis=0)
arr

[[-1.78550814  0.30892182 -0.07755913  0.1700005   1.72282963]
 [-0.15611421  0.15666632  1.59152968  0.49957962  0.71070468]
 [ 0.90490019 -0.01170078  0.60116459  0.5864051  -0.51137933]
 [ 0.96488401  0.19067423 -1.40470439  0.27043365 -1.52099653]]


array([[-1.78550814, -0.01170078, -1.40470439,  0.1700005 , -1.52099653],
       [-0.15611421,  0.15666632, -0.07755913,  0.27043365, -0.51137933],
       [ 0.90490019,  0.19067423,  0.60116459,  0.49957962,  0.71070468],
       [ 0.96488401,  0.30892182,  1.59152968,  0.5864051 ,  1.72282963]])

In [290]:
a = np.array([1,2,3])
b= np.array([3,4,5])
np.setdiff1d(a,b)

array([1, 2])

In [292]:
arr1 = np.arange(10)
arr2 = np.arange(20)
np.savez('test.npz', aa =arr1 , bb=arr2)
!ls


'chapter 4.ipynb'   test.npz


In [297]:
arr1 = np.arange(10)
arr2 = np.arange(20)
np.savez('test.npz', aa =arr1 , bb=arr2)
!ls
ok = np.load('test.npz')
ok['bb']

'chapter 4.ipynb'   test.npz


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [315]:
arr1 = np.arange(6).reshape(2,3)
arr1
arr2 = np.ones(3)
print(arr2)
np.dot(arr1,arr2).shape

[1. 1. 1.]


(2,)

In [331]:
X = np.random.randn(5,5)
mat = X.T.dot(X)
# print(mat)
print(np.linalg.inv(mat).dot(mat))

[[ 1.00000000e+00  6.12837829e-15 -1.44254839e-14  7.12807951e-14
   1.09821043e-14]
 [-1.56107415e-14  1.00000000e+00  2.99859377e-14 -6.51257465e-14
  -2.08611526e-14]
 [ 4.48874611e-15  1.85933940e-15  1.00000000e+00  1.29114967e-14
   1.24025883e-15]
 [-6.62855668e-15  8.11011086e-16  9.94734032e-15  1.00000000e+00
  -4.01380692e-15]
 [ 3.81439283e-15  1.05786224e-14 -1.50541126e-14  4.76170560e-14
   1.00000000e+00]]


In [482]:
sam = np.random.randn(1,20)
print(sam)


[[ 0.82420861 -2.44715781 -0.49755629  0.0209231  -0.33078203 -0.70337744
  -0.11411309 -1.00441521 -1.03141845  0.12412918  1.49523075  1.25897444
   0.17944286  1.67806256 -0.48931312  0.68279491 -0.53851501 -0.73910876
   0.59997686 -0.74967805]]


In [494]:
sam -= sam.mean()
sam /= np.std(sam)

sam.mean(axis=0)

array([ 0.94716389, -2.44552547, -0.4236204 ,  0.11408748, -0.2506611 ,
       -0.6370747 , -0.0259567 , -0.94927686, -0.97728155,  0.22112109,
        1.64307177,  1.39805359,  0.27848616,  1.83268414, -0.41507152,
        0.80050568, -0.46609813, -0.67413117,  0.71461621, -0.68509242])

In [500]:
walk = []
walk.append(2)
walk

[2]

In [535]:
walk = np.array([1,2,3,4,5,4,3,2,2,3,5,7,8,4,3,4,4,3,2,100,100])
# (np.abs(walk) >= 5).argmax()
steps = np.where(walk > 10 , 10, -1)
ok = steps.cumsum()
# ok[0]
ok

array([ -1,  -2,  -3,  -4,  -5,  -6,  -7,  -8,  -9, -10, -11, -12, -13,
       -14, -15, -16, -17, -18, -19,  -9,   1])

In [538]:
draws = np.random.randint(0,2,size=(5,10))
draws

array([[0, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [1, 1, 0, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 1, 1, 1, 0, 1, 1, 0, 1, 0]])

In [551]:
steps = np.where(draws > 0 ,1 ,-1)
steps


array([[-1,  1, -1, -1, -1, -1, -1,  1, -1, -1],
       [ 1,  1, -1,  1, -1,  1, -1,  1, -1, -1],
       [ 1, -1,  1,  1,  1, -1,  1, -1,  1, -1],
       [-1, -1, -1, -1,  1, -1,  1,  1, -1, -1],
       [-1,  1,  1,  1, -1,  1,  1, -1,  1, -1]])

In [556]:
walks = steps.cumsum(1)
walks

array([[-1,  0, -1, -2, -3, -4, -5, -4, -5, -6],
       [ 1,  2,  1,  2,  1,  2,  1,  2,  1,  0],
       [ 1,  0,  1,  2,  3,  2,  3,  2,  3,  2],
       [-1, -2, -3, -4, -3, -4, -3, -2, -3, -4],
       [-1,  0,  1,  2,  1,  2,  3,  2,  3,  2]])

In [559]:
walks.max()
walks.min()



-6

In [570]:
hit2 = (np.abs(walks)>=3).any(1) #每一组有一个只要满足就行
hit2

array([ True, False,  True,  True,  True])

In [572]:
hit2.sum()

4

In [574]:
walks[hit2]

array([[-1,  0, -1, -2, -3, -4, -5, -4, -5, -6],
       [ 1,  0,  1,  2,  3,  2,  3,  2,  3,  2],
       [-1, -2, -3, -4, -3, -4, -3, -2, -3, -4],
       [-1,  0,  1,  2,  1,  2,  3,  2,  3,  2]])

In [582]:
(np.abs(walks[hit2]) > 2 ) .argmax(1)

array([4, 4, 2, 6])